### ISSUE TITLE
in /ccc/all_ccc_history.html.php : order the challenges from smallest down to largest

### ISSUE THREAD

**Issue by RoGGa-69** [RoGGa-69/crawl_cosplay#1]
currently being done with MalcolmRose

**Comment by RoGGa-69** [comment]
also, the 1st set doesn't have the line: Set 1 (scoreboard)

![all_ccc_history](https://github.com/RoGGa-69/crawl_cosplay/assets/119762169/f035e23f-108d-44e9-8bc2-a6e9d51ed9fc)

**Comment by MalcolmRose** [comment]
About to submit a PR that should resolve both issues

**Comment by MalcolmRose** [comment]
Second PR seems to have resolved everything in this issue, feel free to close it :)
