### ISSUE TITLE
when CCTT#1 finishes, modify /tournament/home.html.php to point to /tournament/tresults.html.php

### ISSUE THREAD

**Issue by RoGGa-69** [RoGGa-69/crawl_cosplay#11]
Alkemann did a tresults.html.php file, but it points to the wrong set.

**Comment by dysgwr** [comment]
I don't think there's anything wrong with tresults.html.php. 

For example, [here are the results for the current tournament](https://cosplay.kelbi.org/tournament/tresults?set=32)
