### ISSUE TITLE
player.html.php: CCA table doesn't list Challenges 6-12

### ISSUE THREAD

**Issue by RoGGa-69** [RoGGa-69/crawl_cosplay#3]

**Comment by RoGGa-69** [comment]
![players CCA table](https://github.com/RoGGa-69/crawl_cosplay/assets/119762169/874e1bba-fe24-49eb-b76e-a5bedc22e087)

**Comment by dysgwr** [comment]
I'll take a look at this one this evening.

**Comment by dysgwr** [comment]
Fixed.
